### ISSUE TITLE
Error when running `npm install & npm start`

### ISSUE THREAD

**Issue by domlet** [mapbox/mapbox-gl-accessibility#38]
This demo wasn't working a few minutes ago:
https://labs.mapbox.com/mapbox-gl-accessibility

Here's what I saw first:
<img src="https://user-images.githubusercontent.com/6026447/95109192-1d191480-06f1-11eb-9080-5d7b666e6bce.jpg" width=300>

then second after I added my token to local storage:
<img src="https://user-images.githubusercontent.com/6026447/95109183-19858d80-06f1-11eb-9fbd-583410af0adf.jpg" width=300>

Now the map loads – I have not tested the reader:
<img src="https://user-images.githubusercontent.com/6026447/95109432-6ff2cc00-06f1-11eb-97bd-a62a5a883246.jpg" width=300>

Here’s my error log when I run npm install & npm start
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/domlet/.nvm/versions/node/v10.20.1/bin/node',
1 verbose cli   '/Users/domlet/.nvm/versions/node/v10.20.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.14.5
3 info using node@v10.20.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @mapbox/mapbox-gl-accessibility@0.0.1~prestart: @mapbox/mapbox-gl-accessibility@0.0.1
6 info lifecycle @mapbox/mapbox-gl-accessibility@0.0.1~start: @mapbox/mapbox-gl-accessibility@0.0.1
7 verbose lifecycle @mapbox/mapbox-gl-accessibility@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle @mapbox/mapbox-gl-accessibility@0.0.1~start: PATH: /Users/domlet/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/domlet/Documents/docs/mapbox-gl-accessibility/node_modules/.bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/opt/ruby/bin:/Users/domlet/.nvm/versions/node/v10.20.1/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle @mapbox/mapbox-gl-accessibility@0.0.1~start: CWD: /Users/domlet/Documents/docs/mapbox-gl-accessibility
10 silly lifecycle @mapbox/mapbox-gl-accessibility@0.0.1~start: Args: [ '-c', 'run-p build start:server watch' ]
11 info lifecycle @mapbox/mapbox-gl-accessibility@0.0.1~start: Failed to exec start script
12 verbose stack Error: @mapbox/mapbox-gl-accessibility@0.0.1 start: `run-p build start:server watch`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/Users/domlet/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid @mapbox/mapbox-gl-accessibility@0.0.1
14 verbose cwd /Users/domlet/Documents/docs/mapbox-gl-accessibility
15 verbose Darwin 19.6.0
16 verbose argv "/Users/domlet/.nvm/versions/node/v10.20.1/bin/node" "/Users/domlet/.nvm/versions/node/v10.20.1/bin/npm" "start"
17 verbose node v10.20.1
18 verbose npm  v6.14.5
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error @mapbox/mapbox-gl-accessibility@0.0.1 start: `run-p build start:server watch`
23 error spawn ENOENT
24 error Failed at the @mapbox/mapbox-gl-accessibility@0.0.1 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Just submitting this in case anyone has time to take a look!

**Comment by andrewharvey** [comment]
I'm seeing the same.

**Comment by janinfo** [comment]
Same for me

**Comment by domlet** [comment]
I see that `npm install & npm start` works again, and [the demo](https://labs.mapbox.com/mapbox-gl-accessibility/) works for me with [Chrome Vox extension](https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en):

* [Screen Recording 2020-10-07 at 10.16.54 AM.mov.zip](https://github.com/mapbox/mapbox-gl-accessibility/files/5342622/Screen.Recording.2020-10-07.at.10.16.54.AM.mov.zip)
